[package]
name = "tokio-watch"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.0", features = ["full"] }
winapi = { version = "0.3.9", features = ["winuser", "windef", "minwindef"] }